### PR TITLE
Bioconductor/sweave2rmd: Conversion of MLint_devel.Rnw to Rmd

### LINKED ISSUE #4: Conversion of MLint_devel.Rnw to R markdown
Hi,

I'm volunteering with [Sweave2Rmd](https://github.com/Bioconductor/sweave2rmd)
and we're trying to replace all Bioconductor Sweave vignettes R Markdown
vignettes. Would you be willing to accept a pull request with the R Markdown
version of Introduction to MLint_devel.Rnw from me as a contributor. I'll kindly ask you to
review and accept the pull request. You'll also need to bump the version
number in your DESCRIPTION file so that the build machines will recognize
that a new version is available.

Thanks for your time.

### PR DESCRIPTION
**Pull request by phyleria**
Hello,
As part of the Sweave2rmd project, I have made commits that:

    - Update DESCRIPTION file with BiocStyle, knitr, VignetteBuilder and translator details
    - Convert the MLint_devel.Rnw to Rmd
    - Remove the Rnw file
    

Please find both the PDF and HTML files below:
[PDF](https://bioconductor.org/packages/release/bioc/vignettes/MLInterfaces/inst/doc/MLint_devel.pdf)
[HTML](https://rpubs.com/Phyleria/962306)
    
Kindly review the PR and I will appreciate your feedback. Thank you!
Close #4

### CODE REVIEW

**Comment by vjcitn** [comment]
Thanks @phyleria I will look at this soon.  Look at the rendered html, there is one place where there is too much white space between words, and I think we also need to use message=FALSE in the chunk directive before library(MLInterfaces) to suppress all the package startup chatter.

**Comment by phyleria** [comment]
Thank you @vjcitn
Let me  correct that

**Review by vjcitn — COMMENTED** [review]
Thanks, have you recompiled to rpubs?  Also, it is good practice to name all knitr chunks.  Instead of {r message=FALSE} use {r setup,message=FALSE} [and setup is an arbitrary tag for a chunk that cannot be reused for other chunks.  Naming each chunk helps us debug when vignettes have errors.]

**Comment by phyleria** [comment]
Thank you so much @vjcitn for the explanation. Let me work on the changes and recompile to rpubs

**Comment by phyleria** [comment]
Hello @vjcitn 
I've made the changes from the feedback you gave, kindly review the latest commit I made and let me know if there's anything else I should work on.
I have also updated the doc on rpubs and here's the [link](https://rpubs.com/Phyleria/962306)
Thank you.

**Comment by vjcitn** [comment]
Thank you

**Pull request merged**
